### ISSUE TITLE
Empty HF dataset

### ISSUE THREAD

**Issue by vishaal27** [chenshuang-zhang/imagenet_d#1]
Hey, thanks for the great work and publicly releasing the dataset and code.
However, on the Huggingface link to the dataset, I could not find any of the data files, could you please check if the files are already there or if I am missing something?

Thanks!

**Comment by chenshuang-zhang** [comment]
Hello. Thank you for your interest in ImageNet-D. 

The dataset is available in HuggingFace now.  Could you please check again?

**Comment by vishaal27** [comment]
Thanks, available now!

**Comment by vishaal27** [comment]
Hey, sorry to reopen this issue. 
I am trying to download the dataset using:

```
from huggingface_hub import snapshot_download
repo_id = "zcs15/ImageNet-D"
snapshot_download(repo_id=repo_id, cache_dir='.', allow_patterns=["*.jpg"])
```

However, I get this error when downloading:
```
huggingface_hub.utils._errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6605495c-361a15850aafcc5d333b6a5c;c8367c8f-bcbe-4f0b-9ac9-8f30127e54f5)

Repository Not Found for url: https://huggingface.co/api/models/zcs15/ImageNet-D/revision/main.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
```

Also when I try this:
```
from datasets import load_dataset

dataset - load_dataset("zcs15/ImageNet-D")
```

I get this error:
```
FileNotFoundError: Couldn't find a dataset script at IMAGENET_D/zcs15/ImageNet-D/ImageNet-D.py or any data file in the same directory. Couldn't find 'zcs15/ImageNet-D' on the Hugging Face Hub either: FileNotFoundError: No (supported) data files or dataset script found in zcs15/ImageNet-D.
```

Could you please share the command that you use to download the dataset locally from huggingface. Thanks!

**Comment by chenshuang-zhang** [comment]
Hello. Thank you for reporting this to me! 

I updated the command to download the dataset [here](https://github.com/chenshuang-zhang/imagenet_d?tab=readme-ov-file#dataset).

You can download from Huggingface by `git lfs clone https://huggingface.co/datasets/zcs15/ImageNet-D`. You can also download the dataset from [Google drive](https://drive.google.com/file/d/11zTXmg5yNjZwi8bwc541M1h5tPAVGeQc/view?usp=sharing). Choose the method that works best for you.

Let me know if there are other problems.

**Comment by vishaal27** [comment]
Great thanks, I am using the google drive link, and now everything works! Closing this issue now!
