### ISSUE TITLE
Releasing Synthetic-Easy?

### ISSUE THREAD

**Issue by vishaal27** [chenshuang-zhang/imagenet_d#2]
Hey, are there also plans to release the Synthetic-easy dataset that you used for your testing results in table 2 and the fine-tuning results in table 6? How big is that dataset?

Thanks!

**Comment by chenshuang-zhang** [comment]
Hello.  Thanks for your advice. At the moment, there are no plans to release the Synthetic-easy dataset. However, we're happy to share some information for your reference.

Regarding Table 2, the total size of dataset is on the scale of millions, which is generated following Table 1. As for Table 6, the training set consists of data in the hundreds of thousands. For training details of Table 6, please refer to Section 7 in the appendix.

**Comment by vishaal27** [comment]
Thanks, closing!
