### ISSUE TITLE
WordNet ID of the labels

### ISSUE THREAD

**Issue by hayakae** [chenshuang-zhang/imagenet_d#5]
Thank you for the wonderful work!
I would like to use your dataset for validation in ImageNet classification. Is there a correspondence list for the labels in your dataset and WordNet ID?

Thanks.

**Comment by chenshuang-zhang** [comment]
Thank you for your interest in this paper. For testing the ImagNet model, please refer to:

- [Evaluate vision models pretrained on Imagenet-1k](https://github.com/chenshuang-zhang/imagenet_d#evaluate-vision-models-pretrained-on-imagenet-1k)
- [Preprocessing imgnet_d2imgnet_id.txt](https://github.com/chenshuang-zhang/imagenet_d/blob/main/preprocessing/imgnet_d2imgnet_id.txt)

Thank you.
